
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: service-order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/service-order?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: xuge

  #配置redis
  redis:
    port: 6379
    host: 192.168.70.130



# 打印日志
logging:
  level:
    com.baomidou.mybatisplus: debug
# 打印SQL语句
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: 0

# todo 并发测试环境准备遗留问题
#spring:
#    profiles: 8089
server:
  port: 8089
#spring:
#    profiles: 8008
#server:
#  port: 8008
